USE [master]
GO

/****** Object:  Database [Task]    Script Date: 5/1/2021 11:42:49 AM ******/
CREATE DATABASE [Task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Task', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Task.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Task_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Task_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Task] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Task] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Task] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Task] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Task] SET ARITHABORT OFF 
GO

ALTER DATABASE [Task] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Task] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Task] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Task] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Task] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Task] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Task] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Task] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Task] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Task] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Task] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Task] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Task] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Task] SET  MULTI_USER 
GO

ALTER DATABASE [Task] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Task] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Task] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Task] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Task] SET QUERY_STORE = OFF
GO

USE [Task]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Task] SET  READ_WRITE 
GO

